import type { Metadata } from "next";
import "./globals.css";

import { inter, montserrat, karla, oxygen, playball, racing_sans_one, galada, mystery_quest} from '@/font/fonts';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${inter.variable} ${montserrat.variable} ${karla.variable} ${oxygen.variable} ${playball.variable} ${racing_sans_one.variable} ${galada.variable} ${mystery_quest.variable} `}>
        {children}
      </body>
    </html>
  );
}
